# https://developer.github.com/v3/repos/#edit
repository:
  # make the repository private
  private: true
  # enable issues for the repository
  has_issues: true
  # disable projects for the repository
  has_projects: false
  # enable wiki for the repository
  has_wiki: true
  # make master the default branch for the repository
  default_branch: master
  # allow squash-merging pull requests for the repository
  allow_squash_merge: true
  # prevent merging pull requests with merge commits for the repository
  allow_merge_commit: false
  # prevent rebase-merging pull requests for the repository
  allow_rebase_merge: false

teams:
  - name: engineers
    permission: maintain
  - name: leads
    permission: admin

# https://developer.github.com/v3/repos/branches/#update-branch-protection
branches:
  - name: master
    protection:
      # require pull request reviews before merging
      required_pull_request_reviews:
        # require at least one approving review on a pull request, before merging
        required_approving_review_count: 1
        # dismiss approving reviews when someone pushes a new commit
        dismiss_stale_reviews: true
        # do not blocks merging a pull request until code owners review them
        require_code_owner_reviews: false
        # restrict pull request reviews dismissal to leads team
        dismissal_restrictions:
          teams:
            - leads
      # require status checks to pass before merging
      required_status_checks:
        # require branches to be up to date before merging
        strict: true
        # required status checks in order to merge into this branch
        contexts:
          - "Semantic Pull Request"
          - "ci/circleci: checks"
      # do not enforce all configured restrictions for administrators
      enforce_admins: null
      # restrict who can push to this branch to leads team
      restrictions:
        teams:
          - leads
