version: '2.4'
services:
  node:
    ports:
      - '30260:9229'
    tty: true
    stdin_open: true
    container_name: transactions
    env_file:
      - ./.env
    build:
      context: .
      args:
        - NPM_TOKEN
    user: 'node:node'
    volumes:
      - '.:/home/node/app:rw'

