version: '3'
services:
  node:
    tty: true
    stdin_open: true
    container_name: transactions
    env_file:
      - ./.env
    build:
      context: .
      args:
        - NPM_TOKEN
    volumes:
      - .:/var/code:rw
    entrypoint: './startup.sh'
