version: 1

# docs: https://dependabot.com/docs/config-file/
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "abdelrahman-elkady"
      - "mohamed-ashour"
      - "omarsafwany"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "all"
      - match:
          dependency_type: "indirect"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "chore"
      include_scope: true
